development:
  adapter: postgresql
  encoding: unicode
  database: careersgapp_development
  pool: 5
  username: jamesdelacruz
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: careersgapp_test
  pool: 5
  username: jamesdelacruz
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: <%= ENV['RDS_DB_NAME'] %>
#   username: <%= ENV['RDS_USERNAME'] %>
#   password: <%= ENV['RDS_PASSWORD'] %>
#   host: <%= ENV['RDS_HOSTNAME'] %>
#   port: <%= ENV['RDS_PORT'] %>
#
